image: leocamilo/bitbucket-pipeline-aws-serverless:0.0.1

pipelines:
  default:
    - step:
        name: deploy solution
        deployment: Develop
        services:
          - docker
        caches:
          - docker
          - pip
          - node
        script:
          - pip3 install awscli --upgrade --user
          - export PATH=~/.local/bin:$PATH
          - cd infra && npm install && serverless deploy --stage dev && cd ..
          - cd utils-shared-lib && npm install && serverless deploy --stage dev && cd ..
          - cd analytics && npm install && serverless deploy --stage dev && cd ..
          - cd orchestration && npm install && serverless deploy --stage dev && cd ..
