service: webinar-orchestration

plugins:
  - serverless-step-functions

custom:
  tags: ${file(../tags.yml)}
  prefix: ${self:service}-${self:provider.stage}
  analysisProject: webinar-analysis-${self:provider.stage}
  infraProject: webinar-infra-${self:provider.stage}
  analytics:
    rankingRegions: ${cf:${self:custom.analysisProject}.ApplyRankingRegionsLambdaFunctionQualifiedArn}
    emailCountByAge: ${cf:${self:custom.analysisProject}.ApplyEmailCountByAgeLambdaFunctionQualifiedArn}
    textQualityScore: ${cf:${self:custom.analysisProject}.ApplyTextQualityScoreLambdaFunctionQualifiedArn}
    sentimentAnalysis: ${cf:${self:custom.analysisProject}.ApplySentimentAnalysisLambdaFunctionQualifiedArn}
    clusteringMailslv1: ${cf:${self:custom.analysisProject}.ApplyClusteringMailslv1LambdaFunctionQualifiedArn}
    clusteringMailslv2: ${cf:${self:custom.analysisProject}.ApplyClusteringMailslv2LambdaFunctionQualifiedArn}
    complaintsWithoutMultiline: ${cf:${self:custom.analysisProject}.ApplyComplaintsWithoutMultilineLambdaFunctionQualifiedArn}
    textQualityScoreWithComprehend: ${cf:${self:custom.analysisProject}.ApplyTextQualityScoreWithComprehendLambdaFunctionQualifiedArn}
    textQualityPriority: ${cf:${self:custom.analysisProject}.ApplyTextQualityPriorityLambdaFunctionQualifiedArn}
    createWordcloud: ${cf:${self:custom.analysisProject}.CreateWordcloudLambdaFunctionQualifiedArn}
    joinData: ${cf:${self:custom.analysisProject}.JoinDataLambdaFunctionQualifiedArn}
  infra:
    createClusterEndpoint: ${cf:${self:custom.infraProject}.CreateClusterEndpointLambdaFunctionQualifiedArn}
    deleteClusterEndpoint: ${cf:${self:custom.infraProject}.DeleteClusterEndpointLambdaFunctionQualifiedArn}
    crawler: ${cf:${self:custom.infraProject}.CrawlerLambdaFunctionQualifiedArn}


provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  runtime: python3.7
  stackTags: ${self:custom.tags}
  deploymentBucket: kranio-serverless-deployments-us-east-2

  
stepFunctions:
  validate: true
  stateMachines:
    WebinarEtlStateMachine:
      name: WebinarEtlStateMachine
      tags: ${self:custom.tags}
      definition:
        StartAt: TransformationsParallel
        States:
          TransformationsParallel:
            Type: Parallel
            Branches:
              - StartAt: TextQualityScore
                States:
                  TextQualityScore:
                    Type: Task
                    Resource: ${self:custom.analytics.textQualityScoreWithComprehend}
                    Next: GeneratePriority
                  GeneratePriority:
                    Type: Task
                    Resource: ${self:custom.analytics.textQualityPriority}
                    End: true
              
              - StartAt: EmailCountByAge
                States:
                  EmailCountByAge:
                    Type: Task
                    Resource: ${self:custom.analytics.emailCountByAge}
                    End: true
              
              - StartAt: RankingRegionsComplaints
                States:
                  RankingRegionsComplaints:
                    Type: Task
                    Resource: ${self:custom.analytics.rankingRegions}
                    End: true
              
              - StartAt: SentimentAnalysis
                States:
                  SentimentAnalysis:
                    Type: Task
                    Resource: ${self:custom.analytics.sentimentAnalysis}
                    End: true
              
              - StartAt: ComplaintsWithoutMultiline
                States:
                  ComplaintsWithoutMultiline:
                    Type: Task
                    Resource: ${self:custom.analytics.complaintsWithoutMultiline}
                    End: true
              
              # - StartAt: CreateClusterEndpoint
              #   States:
              #     CreateClusterEndpoint:
              #       Type: Task
              #       Resource: ${self:custom.infra.createClusterEndpoint}
              #       Next: ClusteringMailsLevel1
              #     ClusteringMailsLevel1:
              #       Type: Task
              #       Resource: ${self:custom.analytics.clusteringMailslv1}
              #       Next: ClusteringMailsLevel2
              #     ClusteringMailsLevel2:
              #       Type: Task
              #       Resource: ${self:custom.analytics.clusteringMailslv2}
              #       Next: DeleteClusterEndpoint
              #     DeleteClusterEndpoint:
              #       Type: Task
              #       Resource: ${self:custom.infra.deleteClusterEndpoint}
              #       End: true
            Next: JoiningData

          JoiningData:
            Type: Task
            Resource: ${self:custom.analytics.joinData}
            Next: WordCloud

          WordCloud:
            Type: Task
            Resource: ${self:custom.analytics.createWordcloud}
            Next: StartCrawler

          StartCrawler:
            Type: Task
            Resource: ${self:custom.infra.crawler}
            End: true
